version: '3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: docker/py37.Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    environment:
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
        - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es
      - worker
      - rabbit
      - redis

  rabbit:
    restart: unless-stopped
    image: rabbitmq

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  worker:
    build:
      context: .
      dockerfile: docker/py37.Dockerfile
    command: celery -A core worker -l info
    environment:
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
        - .:/code
    depends_on:
      - db
      - rabbit
      - redis
  es:
    build:
      context: .
      dockerfile: docker/es.Dockerfile
    ports:
      - "9200:9200"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/tmp/share/elasticsearch/data

volumes:
  data01:
    driver: local