version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - db:/var/lib/postgresql/data
  app:
    image: python:3.9
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es
      - rabbit
      - redis

  rabbit:
    restart: unless-stopped
    image: rabbitmq

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  worker:
    image: python:3.9
    command: celery -A core worker -l info
    depends_on:
      - db
      - rabbit
      - redis

  es:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    # environment:
      # - bootstrap.memory_lock=true
      # - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - esdata:/tmp/share/elasticsearch/data

# volumes:
#   esdata:
#     driver: azure_file
#     driver_opts:
#       share_name: fpvshare
#       storage_account_name: fpvstorage
#   db:
#     driver: azure_file
#     driver_opts:
#       share_name: fpvshare
#       storage_account_name: fpvstorage
