version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: docker/py37.Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:80"
    depends_on:
      - db
      - es
      - rabbit
      - redis

  rabbit:
    restart: unless-stopped
    image: rabbitmq

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  celery_worker:
    command: celery -A core worker -l info
    build:
      context: .
      dockerfile: docker/py37.Dockerfile
    depends_on:
      - db
      - rabbit
      - redis

  es:
    build:
      context: .
      dockerfile: docker/es.Dockerfile
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/tmp/share/elasticsearch/data
      - data01:/tmp/share/elasticsearch/data

volumes:
  data01:
    driver: local
