# Generated by Django 3.0.8 on 2021-10-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='not_scrapable_reason',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='The reason why this store was not scrapable'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_class',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The css class of the main image of the product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The html tag of the main image of the product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_thumb_class',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The css class of the thumbnail images of the product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_thumb_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The html tag of the thumbnail images of the product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='search_next_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The nearest css class from where to get the next page link'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=770, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('name', models.CharField(max_length=512, verbose_name='The name of the product')),
                ('description', models.TextField(verbose_name='Description of the product')),
                ('price', models.FloatField(verbose_name='Price of the product')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('average_stars', models.FloatField(null=True, verbose_name='The average stars from reviews')),
                ('image', models.URLField(null=True, verbose_name="The url of the product's image")),
                ('link', models.URLField(default='', verbose_name="The url of the product's page")),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
