# Generated by Django 3.0.8 on 2021-10-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_store_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='locale',
            field=models.CharField(choices=[('us_US', 'American'), ('it_IT', 'European')], default='it_IT', help_text='Used to scrape prices', max_length=5, verbose_name='Locale used in the store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('USA', 'United States'), ('IT', 'Italy'), ('OTH', 'Other')], max_length=3, verbose_name='Region of the store'),
        ),
    ]
