# Generated by Django 3.0.8 on 2021-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20211024_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Import date'),
        ),
    ]
