# Generated by Django 3.0.8 on 2021-10-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_product_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='locale',
            field=models.CharField(choices=[('en_US', 'American'), ('it_IT', 'European')], default='it_IT', help_text='Used to scrape prices', max_length=5, verbose_name='Locale used in the store'),
        ),
    ]
