# Generated by Django 3.0.8 on 2021-10-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20211025_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_stars',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.FloatField(blank=True, null=True, verbose_name='The average stars from reviews'),
        ),
        migrations.AddField(
            model_name='store',
            name='product_is_available_class',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The css class to know if the product is available'),
        ),
        migrations.AddField(
            model_name='store',
            name='product_is_available_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The html tag to know if the product is available'),
        ),
        migrations.AlterField(
            model_name='store',
            name='locale',
            field=models.CharField(choices=[('en_US', 'American'), ('it_IT', 'European')], default='it_IT', help_text='If the store uses , as decimal separator choose European', max_length=5, verbose_name='Locale used in the store'),
        ),
    ]
