# Generated by Django 3.0.8 on 2021-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20211025_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_is_available_match',
            field=models.CharField(blank=True, default='disponibil', max_length=64, null=True, verbose_name='The available keyword used for the store'),
        ),
    ]
