# Generated by Django 3.0.8 on 2021-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_store_product_is_available_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_is_available_match',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Regex to match if the product is in stock'),
        ),
    ]
