# Generated by Django 3.0.8 on 2021-10-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20211025_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('min_shipping_time', models.SmallIntegerField(default=1, verbose_name='Minimum Shipping Time in days')),
                ('max_shipping_time', models.SmallIntegerField(blank=True, null=True, verbose_name='Maximum Shipping Time in days')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Shipping Cost')),
                ('min_price_free_shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Minimum price to get free shipping')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='search.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
