# Generated by Django 3.0.8 on 2021-11-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20211029_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_variations_class',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The css class to know if the product has variations'),
        ),
        migrations.AddField(
            model_name='store',
            name='product_variations_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The html tag to know if the product has variations'),
        ),
    ]
