# Generated by Django 3.0.8 on 2021-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20211121_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name_it',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
