# Generated by Django 3.0.8 on 2021-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20211121_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(max_length=1024, null=True, verbose_name="The url of the product's image"),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='', max_length=1024, verbose_name="The url of the product's page"),
        ),
    ]
