# Generated by Django 3.2.9 on 2021-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20211203_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='The name of the country'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_it',
            field=models.CharField(max_length=128, null=True, verbose_name='The name of the country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=128, verbose_name='The name of the country'),
        ),
    ]
