# Generated by Django 3.2.9 on 2021-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20211203_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='min_price_free_shipping',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='min_price_shipping_condition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Minimum price to get this shipping'),
        ),
    ]
