# Generated by Django 3.2.9 on 2021-12-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_auto_20211203_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicked_after_seconds', models.FloatField(verbose_name='Clicked After Seconds')),
                ('search_query', models.CharField(max_length=512, verbose_name='Search query')),
                ('page', models.IntegerField(verbose_name='Result page')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='search.product')),
            ],
            options={
                'verbose_name_plural': 'Clicked Products',
            },
        ),
    ]
