# Generated by Django 3.2.9 on 2021-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_clickedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(verbose_name='URL of the store')),
                ('is_spam', models.BooleanField(default=False, verbose_name='Is Spam')),
                ('is_already_present', models.BooleanField(verbose_name='Is the store already present')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
