# Generated by Django 3.2.9 on 2021-12-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_requestedstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='is_vat_included',
            field=models.BooleanField(default=True, verbose_name='Is VAT included?'),
        ),
    ]
