# Generated by Django 3.2.9 on 2021-12-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_shippingmethod_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=256, verbose_name='The text to search on the stores')),
                ('priority', models.CharField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1, max_length=6, verbose_name='Import Priority')),
                ('priority_score', models.FloatField(default=1, verbose_name='Priority Score')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-priority_score',),
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='import_query',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='search.importquery'),
        ),
    ]
