# Generated by Django 3.2.9 on 2021-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20211211_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importquery',
            options={'ordering': ('-priority_score',), 'verbose_name': 'Import Query', 'verbose_name_plural': 'Import Queries'},
        ),
        migrations.AlterField(
            model_name='importquery',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1, max_length=6, verbose_name='Import Priority'),
        ),
    ]
