# Generated by Django 3.2.9 on 2021-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_auto_20211211_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='importquery',
            name='products_clicks',
            field=models.IntegerField(default=0, verbose_name='Clicks of the imported products'),
        ),
    ]
