# Generated by Django 3.2.9 on 2021-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_auto_20211224_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='EUR', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='EUR', max_length=3, verbose_name='Default Currency'),
        ),
    ]
