# Generated by Django 3.2.9 on 2022-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0033_auto_20220210_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='search_page_param',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='The query param used in alternative to the next page link'),
        ),
    ]
