# Generated by Django 3.2.9 on 2022-03-26 09:40
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_auto_20220312_1252'),
    ]

    operations = [
        TrigramExtension(),
    ]
