# Generated by Django 3.2.9 on 2022-03-12 13:16
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_auto_20220312_1252'),
    ]

    operations = [
        TrigramExtension(),
    ]
