# Generated by Django 3.2.9 on 2022-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0038_auto_20220312_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/', verbose_name='Logo'),
        ),
    ]
