# Generated by Django 3.2.9 on 2022-04-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_create_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Shipping Cost')),
                ('min_price_shipping_condition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Minimum price to get this shipping')),
                ('is_weight_dependent', models.BooleanField(default=False, verbose_name='Does the price depend on the shipping weight?')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_shipping_methods', to='search.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
