# Generated by Django 3.2.9 on 2022-03-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_store_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name of the brand')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_it', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('logo', models.ImageField(upload_to='', verbose_name='Brand Logo')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Is an hot brand?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importquery',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='import_queries', to='search.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='search.brand'),
        ),
    ]
