name: Linux Container Node Workflow

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: liuuuk311acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -f docker/py37.Dockerfile -t liuuuk311acr.azurecr.io/app:${{ github.sha }} .
        docker build -f docker/es.Dockerfile -t liuuuk311acr.azurecr.io/es:${{ github.sha }} .
        docker push liuuuk311acr.azurecr.io/app:${{ github.sha }} 
        docker push liuuuk311acr.azurecr.io/es:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'fpvscraper'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: |
          'liuuuk311acr.azurecr.io/app:${{ github.sha }}'
          'liuuuk311acr.azurecr.io/es:${{ github.sha }}'
          
